name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: List project root directory (initial check)
      - name: List root directory
        run: ls -la

      # Step 3: Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Step 4: Set up Node.js (for tree-sitter CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use the latest stable Node.js version

      # Step 5: Install tree-sitter CLI globally
      - name: Install tree-sitter CLI
        run: npm install -g tree-sitter-cli

      # Step 6: Generate the parser from grammar.js
      - name: Generate Tree-sitter parser
        run: |
          tree-sitter generate
          echo "Listing src directory after generation:"
          ls -la src

      # Step 7: Build the Rust project
      - name: Build with Cargo
        run: |
          cargo build --verbose
          echo "Listing target/debug directory after build:"
          ls -la target/debug

      # Step 8: Run tests
      - name: Run tests
        run: |
          cargo test --verbose
          echo "Listing target/debug/deps after tests:"
          ls -la target/debug/deps